### ISSUE TITLE
Apply to PaperMC (or better PurpurMC)

### ISSUE THREAD

**Issue by nfsprodriver** [phase/1.16-to-1.17#1]
Great to see you generated patch files from latest stable to snapshot! Is there a possibility to apply these patches to PaperMC/PurpurMC? If so, do you suggest it'll be very buggy?

**Comment by phase** [comment]
These patches aren't actually usable, they're a source level diff of two decompiled jars. I only use them to look at the source level changes Mojang is making. Your best bet would probably be to use a dev [build of ViaVersion](https://github.com/ViaVersion/ViaVersion/commit/ab376dc562e0fd5cd76d8107072c6bbe0e4a9358).

**Comment by nfsprodriver** [comment]
Cool, thank you for the hint :-)
